api:
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix:   /

api_machin:
  pattern: /api/v1/example
  defaults: { _controller:ApiBundle:Default:Index }

new_game:
  pattern: /api/newgame/{difficulty}/{playerId}
  defaults: { _controller:ApiBundle:Default:NewGame }

save_score:
  pattern: /api/savescore/{matchId}/{playerId}/{time}
  defaults: { _controller:ApiBundle:Default:SaveScore }

get_timer:
  pattern: /api/gettimer/{matchId}/{playerId}
  defaults: { _controller:ApiBundle:Default:GetTimer }

get_recent_results:
  pattern: /api/getrecentresults/{playerId}
  defaults: { _controller:ApiBundle:Default:GetRecentResults }

forfeit_match:
  pattern: /api/forfeitmatch/{matchId}/{playerId}
  defaults: { _controller:ApiBundle:Default:ForfeitMatch }

get_match_status:
  pattern: /api/getmatchstatus/{matchId}/{playerId}
  defaults: { _controller:ApiBundle:Default:GetMatchStatus }